package: url
version: '2.0.0-beta3'
author: Thomas Blum
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:url'
    perm: admin[]
    pjax: false
    icon: rex-icon fa fa-anchor
    subpages:
        generator:
            title: 'translate:generator'
            subpages:
                profiles:
                    title: 'translate:url_generator_profiles'
                urls:
                    title: 'translate:url_generator_urls_generated'
        help:
            title: translate:url_generator_help
            pjax: false
            subPath: README.md
            itemclass: pull-right
        clear_cache: { title: 'translate:url_subpage_clear_cache', itemclass: 'pull-right', linkclass: 'btn btn-delete', href: { page: url/generator/urls, func: refresh } }

requires:
    redaxo: ^5.4.0
    packages:
        yrewrite: ^2.2.0
    php:
        extensions: [intl]
        version: ^7.0

#load: late
